### ISSUE TITLE
[Feature] - script to format source 

### ISSUE THREAD

**Issue by ndcunningham** [allenhwkim/ngui-common#11]
We should have a script that auto formats the code before making a PR

Everyone's machine / environment is set up differently the script will make it consistent.

**Comment by hakimio** [comment]
[tslint](https://github.com/allenhwkim/ngui-common/blob/master/tslint.json) should already enforce most of the coding style. The only thing missing, I think, is identation (4 spaces?) and line breaks (unix style "\n"?).

**Comment by hakimio** [comment]
@allenhwkim 2 space or 4 space indentation?

**Comment by ndcunningham** [comment]
yes but i can remove those coding  styles to fit my own.
I have prettier installed I checkout out a branch and saved and the format is different from what the original was.
Example My decorators are not inline with variable which is associated with it like C# / Java they are on their own line.

**Comment by hakimio** [comment]
I don't think the script you are looking for is in the scope of this project.

**Comment by ndcunningham** [comment]
i am not looking for a script for myself it's for the project.

**Comment by allenhwkim** [comment]
I thought this would satisfy all linting issues.
These two lines prevents unstyles commits.

https://github.com/allenhwkim/ngui-common/blob/master/package.json#L23
https://github.com/allenhwkim/ngui-common/blob/master/package.json#L76

**Comment by ndcunningham** [comment]
Actually when i rum `npm run lint`
it gives me an error for files which i have not touched
https://github.com/allenhwkim/ngui-common/blob/master/projects/ngui-common/src/lib/ngui-utils/src/konsole.ts#L49

So i would think it is not working. Additionally, even if the lint picks up that the code format is wrong i think an auto-format is handy to run for a pre-commit hook for the entire project. Based on the same tsconfig you have reference before.

**Comment by hakimio** [comment]
I'll fix that lint error, but there are no plans to introduce any extra scripts for formatting code. tslint already has auto-fixers for most things.

**Comment by hakimio** [comment]
If you pull the latest changes, tslint will be happy.
A bit later I'll add a couple more rules to make it a bit stricter.

**Comment by hakimio** [comment]
- I have added few more commonly used linting rules.
- You should never change third party project coding styles to fit your own needs.
- Since we are running tslint with "--fix" argument, it will try to automatically fix style issues when possible. There is no need for any extra script.

**Comment by allenhwkim** [comment]
@hakimio thanks I agree with you.
