### ISSUE TITLE
[Documentation Fix] NguiInviewComponent Documentation Typos

### ISSUE THREAD

**Issue by ayazmaroof** [allenhwkim/ngui-common#13]
I was recently trying to use the ngui-inview in my Angular project by following the documentation [here](https://rawgit.com/allenhwkim/ngui-common/master/documentation/components/NguiInviewComponent.html) and noticed that the documentation does not match the actual code in the file projects/ngui-common/src/lib/ngui-inview/src/ngui-inview.component.ts
For example, the element in the documentation is `<ngui-in-view/>` but the actual selector according to the code is 'ngui-inview'. Moreover, I think some of the output event names don't match either. 

I am going to create a PR to fix these. Just wanted to mention it here so that everyone is aware.

**Comment by ayazmaroof** [comment]
@hakimio or @allenhwkim I fixed it in my local feature branch. Do you mind giving me permission to push my feature branch to github so that I can create PR for you to review?

**Comment by hakimio** [comment]
@ayazmaroof you don't need any extra permissions to fork the project, create new branch in your repository and then submit PR to this repository.

**Comment by ayazmaroof** [comment]
@hakimio Thanks! Just created the [PR](https://github.com/allenhwkim/ngui-common/pull/14).

**Comment by hakimio** [comment]
Thanks for the PR.
