### ISSUE TITLE
error with testing with angular 9

### ISSUE THREAD

**Issue by wolfpackt99** [allenhwkim/ngui-common#15]
Entry point '@ngui/common' contains deep imports into 'D:/a/1/s/node_modules/rxjs/internal/observable/fromEvent'. This is probably not a problem, but may cause the compilation of entry points to be out of order.

Im guessing this to be an issue with Ivy.

[fromEvent usage](https://github.com/allenhwkim/ngui-common/search?q=fromEvent&unscoped_q=fromEvent)

**Comment by hakimio** [comment]
Yes, it's from Ivy. I'll try to fix them sometime this week.

**Comment by hakimio** [comment]
@wolfpackt99 I've published a new version for Angular 10. Let me know if it works for you.
