### ISSUE TITLE
Pagination on scroll

### ISSUE THREAD

**Issue by MahmoudTarekAli** [allenhwkim/ngui-common#20]
How can i call function to get next page when i reach end of the scroll (window scroll) i used bottomInview but i do not understand how it works

<img width="387" alt="file" src="https://user-images.githubusercontent.com/20236453/106561530-83903100-6531-11eb-95d2-99fadd595f8b.PNG">
in dom there is no new ngui-view-page created for each page ... how can i do this with pagination on scroll

**Comment by hakimio** [comment]
There is a demo showing how it works:
https://github.com/allenhwkim/ngui-common/blob/master/src/app/list-module-test/virtual-list-component.ts#L12
https://github.com/allenhwkim/ngui-common/blob/master/src/app/list-module-test/virtual-list-component.ts#L45

Basically you have to increment the last loaded page yourself after each page load and once the results are loaded add them to the virtual list using the event argument:
```ts
  pageToLoad = 1;

  loadItems(virtualList: any): void {
    this.myItemService.load(this.pageToLoad).subscribe(items => {
      virtualList.addList(items);
      this.pageToLoad++;
    });
  }
```

```

**Comment by hakimio** [comment]
Also, following seems to be wrong in your code:
```html
<ng-template let-items="userPosts">
```
It should be:
```html
<ng-template let-userPosts="items">
```

**Comment by MahmoudTarekAli** [comment]
Thanks for your fast response and your help ... but there is weird behavior happens as you can see in uploaded video 

https://user-images.githubusercontent.com/20236453/106649321-106ed500-659a-11eb-9225-4e37546b9cb4.mp4

**Comment by hakimio** [comment]
Sorry, but I can't help just by looking at that screen-cast. You have to provide some code which reproduces this issue. Can you create a demo on http://stackblitz.com/ or some other similar platform?

**Comment by MahmoudTarekAli** [comment]
Thanks for your response, its actually working fine the problem is you just need to remove the text of how many items is hidden.
it shows behind of my content

**Comment by MahmoudTarekAli** [comment]
One more thing please,  i think u remove and add item to view port when it reaches 80%. 
<img width="487" alt="ngui2" src="https://user-images.githubusercontent.com/20236453/107843008-2e290f00-6dd0-11eb-81a8-f0a9c6d34c9c.PNG">
<img width="488" alt="ngui" src="https://user-images.githubusercontent.com/20236453/107843010-31bc9600-6dd0-11eb-9961-b70841f032b5.PNG">

i need to remove item when its 100% out of the viewport not 80% how can i do that .
thanks again for your amazing work

**Comment by hakimio** [comment]
The work was done by @allenhwkim , but I can take a look at your feature requests and submit a PR next week.

**Comment by MahmoudTarekAli** [comment]
Thanks for your response and please do not forget to remove the div tag of how many items are hidden

**Comment by hakimio** [comment]
@MahmoudTarekAli PR #21

**Comment by hakimio** [comment]
@MahmoudTarekAli I have published a new version on npm. See if it works as you wanted.
