### ISSUE TITLE
Production build (with "aot" enabled) fails when library is imported as a package

### ISSUE THREAD

**Issue by hakimio** [allenhwkim/ngui-common#5]
Steps to reproduce:
* Generate a new Angular app
* Import the package the following way:
`import {NguiInviewModule} from '@ngui/common';`
* Try to build the app:
`ng build --prod`

Result:
`ERROR in : Unexpected value 'NguiInviewModule in C:/<REDACTED>/node_modules/@ngui/common/modules/dist/inview/src/ngui-inview.module.d.ts' imported by the module 'SharedModule in C:/<REDACTED>/src/app/shared/shared.module.ts'. Please add a @NgModule annotation.`

Production build works fine when importing the module directly like you do in your demo app. The issue only occurs when the module is imported from a package.

Following bug reports might be related to the issue:
[ng-packagr#355](https://github.com/dherges/ng-packagr/issues/355)
[ng-packagr#195](https://github.com/dherges/ng-packagr/issues/195)

EDIT:
[Angular issue](https://github.com/angular/angular/issues/23713)
[Angular Pull Request](https://github.com/angular/angular/pull/22856)

**Comment by allenhwkim** [comment]
hmm, thanks for reporting this. Honestly, I have no idea at the moment. :(

**Comment by hakimio** [comment]
Maybe take a look at the bug reports I linked to and see if any of the suggestions mentioned there can help in this case?

**Comment by allenhwkim** [comment]
It seems the solution with `ng-packagr` goes out of my capability.
Asking opinion, should I not use `ng-packagr`, and go back to `webpack`?

**Comment by hakimio** [comment]
I agree with Adam: you should get rid of TypeScript barrels and see if that fixes the build.

**Comment by hakimio** [comment]
Version 0.3.1 still doesn't build...
@allenhwkim If you have some time, maybe you could take a look at this [detailed guide](https://blog.angularindepth.com/creating-a-library-in-angular-6-87799552e7e5) explaining how the library (and the demo app) should be set-up?
